# version: '3.8'
services:
  mongo:
    image: mongo:6
    ports: ['27017:27017']
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports: ['4000:4000']
    environment:
      - MONGO_URI=mongodb://mongo:27017/trackit
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports: ['8081:80']
    depends_on:
      - backend

volumes:
  mongo-data:
