apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackit-backend
  namespace: trackit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trackit-backend
  template:
    metadata:
      labels:
        app: trackit-backend
    spec:
      containers:
      - name: backend
        image: ly20000325/trackit-backend:latest
        env:
        - name: MONGO_URI
          value: mongodb://trackit-mongo:27017/trackit
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: trackit-backend
  namespace: trackit
spec:
  selector:
    app: trackit-backend
  ports:
  - port: 4000
  