apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackit-frontend
  namespace: trackit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trackit-frontend
  template:
    metadata:
      labels:
        app: trackit-frontend
    spec:
      containers:
        - name: frontend
          image: yangli/trackit-frontend:latest  # 或你的镜像地址
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: trackit-frontend
  namespace: trackit
spec:
  type: LoadBalancer
  selector:
    app: trackit-frontend
  ports:
    - port: 80
      targetPort: 80